//! System status and management endpoints for the System page.
//!
//! - GET  /system           — Comprehensive system status
//! - POST /system/reindex   — Trigger full re-index
//! - POST /system/clear-cache — Clear search index and cache
//! - POST /system/git-resync — Trigger full git re-sync (stub -- not yet implemented)
//! - POST /system/reset     — Factory reset (requires confirmation)

mod handlers;
mod types;

#[cfg(test)]
mod tests_endpoints;
#[cfg(test)]
mod tests_unit;

use std::sync::Arc;

use axum::{
    routing::{get, post},
    Router,
};

use crate::state::AppState;

// Re-export all public types so external code sees the same API as before.
pub use types::{
    ActionResponse, CheckPathQuery, CheckPathResponse, ClassificationInfo, ClearCacheResponse,
    HealthInfo, IndexRunInfo, IntegrityCounterInfo, IntegrityInfo, PerformanceInfo, ResetRequest,
    StorageInfo, SystemResponse,
};

// Re-export all handler functions for OpenAPI registration.
pub use handlers::{
    check_path, clear_cache, get_system_status, reset_all, trigger_git_resync, trigger_reindex,
};

// Re-export utoipa __path_* types (generated by #[utoipa::path] on handlers)
pub use handlers::{
    __path_check_path, __path_clear_cache, __path_get_system_status, __path_reset_all,
    __path_trigger_git_resync, __path_trigger_reindex,
};

/// Create the system routes router.
pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route("/system", get(handlers::get_system_status))
        .route("/system/reindex", post(handlers::trigger_reindex))
        .route("/system/clear-cache", post(handlers::clear_cache))
        .route("/system/git-resync", post(handlers::trigger_git_resync))
        .route("/system/reset", post(handlers::reset_all))
        .route("/check-path", get(handlers::check_path))
}
