//! Rollup-table migrations — 15 typed rollup tables generated by
//! `#[derive(RollupTable)]` on `claude_view_stats_rollup::StatsCore`.
//!
//! The migration strings are authored by the proc-macro (single source
//! of truth for schema shape); this module is the mount point into the
//! canonical `migrations()` sequence defined in `super::mod.rs`.
//!
//! Order is `(outer: bucket, inner: dimension)` — matches
//! `stats_core::migrations::STATEMENTS` byte-for-byte. If `TABLE_COUNT`
//! changes, this slice changes by exactly that amount automatically.
//!
//! See `private/config/docs/plans/2026-04-17-cqrs-phase-1-7-design.md §6.2`
//! and `crates/stats-rollup/src/stats_core.rs` for the schema spec.

/// CREATE TABLE statements for the 15 rollup tables, in canonical apply
/// order. Delegates to the proc-macro output so the schema shape cannot
/// drift from the struct definitions Stage C reads and writes.
pub const MIGRATIONS: &[&str] = claude_view_stats_rollup::stats_core::migrations::STATEMENTS;
