//! Plugin management API routes.
//!
//! - GET  /plugins                    -- Unified view of installed + available plugins
//! - POST /plugins/action             -- Mutations (install/update/uninstall/enable/disable)
//! - GET  /plugins/marketplaces       -- List configured marketplaces
//! - POST /plugins/marketplaces/action -- Marketplace mutations (add/remove/update)

mod cli;
mod enrichment;
mod filters;
mod handlers;
mod types;
mod validation;

#[cfg(test)]
mod tests;

use std::sync::Arc;

use axum::{
    routing::{get, post},
    Router,
};

use crate::state::AppState;

// ---------------------------------------------------------------------------
// Re-exports — everything that was `pub` in the original single file
// ---------------------------------------------------------------------------

// Response types
pub use types::{
    AvailablePlugin, MarketplaceActionRequest, MarketplaceInfo, PluginActionRequest,
    PluginActionResponse, PluginInfo, PluginItem, PluginsQuery, PluginsResponse, UserItemInfo,
};

// Filters
pub use filters::{apply_filters, parse_plugin_id};

// Handlers
pub use handlers::{list_marketplaces, list_plugins, marketplace_action};

// utoipa __path_* re-exports (generated by #[utoipa::path] in submodules)
#[allow(unused_imports)]
pub use handlers::__path_list_marketplaces;
#[allow(unused_imports)]
pub use handlers::__path_list_plugins;
#[allow(unused_imports)]
pub use handlers::__path_marketplace_action;

// CLI helpers (pub(crate))
pub(crate) use cli::{invalidate_plugin_cache, run_claude_plugin_in, CliAvailableResponse};

// Validation (pub(crate))
pub(crate) use validation::{
    get_marketplace_lock, validate_plugin_name, validate_scope, VALID_ACTIONS,
};

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route("/plugins", get(handlers::list_plugins))
        .route("/plugins/marketplaces", get(handlers::list_marketplaces))
        .route(
            "/plugins/marketplaces/action",
            post(handlers::marketplace_action),
        )
}
