//! Indexing progress endpoints.
//!
//! - `GET /api/indexing/progress` -- SSE stream (kept for direct-connect production use)
//! - `GET /api/indexing/status`   -- JSON snapshot (reliable through any proxy)

mod handlers;
mod types;

#[cfg(test)]
mod tests;

// Re-export all public items to preserve the module's public API.
pub use handlers::{indexing_progress, indexing_status, router};
// utoipa hidden path types generated by #[utoipa::path] macro.
pub use handlers::__path_indexing_progress;
pub use handlers::__path_indexing_status;
pub use types::IndexingStatusResponse;
