//! GET /api/insights endpoint: Returns computed patterns and insights.
//!
//! This endpoint queries session data from the database, runs the pattern
//! detection engine, and returns scored, ranked insights grouped by tier.

use std::sync::Arc;

use axum::{routing::get, Router};

use crate::state::AppState;

mod db;
mod handler_benchmarks;
mod handler_categories;
mod handler_insights;
mod handler_trends;
pub mod types;

#[cfg(test)]
mod tests;

// Re-export all public types
pub use types::{
    BenchmarksQuery, BenchmarksResponseWithMeta, BestTimeStats, CategoriesMeta, CategoriesQuery,
    CategoriesResponse, CategoryBreakdown, CategoryNode, CategorySummary, ClassificationCoverage,
    EfficiencyStats, InsightsMeta, InsightsOverview, InsightsQuery, InsightsResponse,
    InsightsTrendsMeta, InsightsTrendsResponse, OverallAverages, PatternGroups, TrendsQuery,
    WorkBreakdown,
};

// Re-export handlers
pub use handler_benchmarks::get_benchmarks;
pub use handler_categories::get_categories;
pub use handler_insights::get_insights;
pub use handler_trends::get_insights_trends;

// utoipa __path_* re-exports (generated by #[utoipa::path] in submodules)
#[allow(unused_imports)]
pub use handler_benchmarks::__path_get_benchmarks;
#[allow(unused_imports)]
pub use handler_categories::__path_get_categories;
#[allow(unused_imports)]
pub use handler_insights::__path_get_insights;
#[allow(unused_imports)]
pub use handler_trends::__path_get_insights_trends;

/// Create the insights routes router.
pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route("/insights", get(get_insights))
        .route("/insights/categories", get(get_categories))
        .route("/insights/trends", get(get_insights_trends))
        .route("/insights/benchmarks", get(get_benchmarks))
}
