//! CLI session management API routes.
//!
//! Manages tmux-based CLI sessions that run Claude Code.
//! Sessions are tracked in-memory with periodic health checks
//! against the actual tmux process state.
//!
//! - POST   /cli-sessions      -- Create a new CLI session
//! - DELETE /cli-sessions/{id} -- Kill a CLI session

pub mod handlers;
pub mod health;
pub mod lifecycle_debug;
pub mod reconcile;
pub mod ring_buffer;
pub mod terminal;
pub mod terminal_ws;
pub mod tmux;
pub mod tmux_index;
pub mod types;

#[cfg(test)]
mod tests;

use axum::{
    routing::{delete, post},
    Router,
};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use crate::state::AppState;

/// Oneshot waiters for pid.json Born events.
/// Create handler registers a sender keyed by pane PID.
/// Born handler (sessions_lifecycle) resolves it with the sessionId.
pub type BornWaiters = Arc<Mutex<HashMap<u32, tokio::sync::oneshot::Sender<String>>>>;

// Re-export key types.
pub use tmux::{RealTmux, TmuxCommand};
pub use tmux_index::TmuxSessionIndex;
pub use types::{CliSession, CliSessionStatus, CreateRequest, CreateResponse};

// Re-export handlers for OpenAPI path reference.
pub use handlers::{create_session, kill_session};

// utoipa __path_* re-exports (generated by #[utoipa::path] in submodules)
#[allow(unused_imports)]
pub use handlers::{__path_create_session, __path_kill_session};

/// CLI sessions API router.
pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route("/cli-sessions", post(handlers::create_session))
        .route("/cli-sessions/{id}", delete(handlers::kill_session))
}
