// This file is auto-generated by `supabase gen types typescript`.
// DO NOT EDIT MANUALLY. Re-run the codegen command after schema changes:
//   supabase gen types typescript --project-id $SUPABASE_DEV_PROJECT_REF > packages/shared/src/types/supabase.generated.ts
//
// Also re-synced via the Supabase MCP `generate_typescript_types` tool —
// keep this file in step with the live schema of the claude-view project
// (ref: iebjyftoadahqptmfcio).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.1'
  }
  public: {
    Tables: {
      device_events: {
        Row: {
          device_id: string
          event: string
          id: number
          metadata: Json
          occurred_at: string
          user_id: string
        }
        Insert: {
          device_id: string
          event: string
          id?: number
          metadata?: Json
          occurred_at?: string
          user_id: string
        }
        Update: {
          device_id?: string
          event?: string
          id?: number
          metadata?: Json
          occurred_at?: string
          user_id?: string
        }
        Relationships: []
      }
      devices: {
        Row: {
          app_version: string | null
          created_at: string
          device_id: string
          display_name: string
          ed25519_pubkey: string
          last_ip: unknown
          last_seen_at: string
          last_user_agent: string | null
          os_version: string | null
          platform: string
          revoked_at: string | null
          revoked_reason: string | null
          user_id: string
          x25519_pubkey: string
        }
        Insert: {
          app_version?: string | null
          created_at?: string
          device_id: string
          display_name: string
          ed25519_pubkey: string
          last_ip?: unknown
          last_seen_at?: string
          last_user_agent?: string | null
          os_version?: string | null
          platform: string
          revoked_at?: string | null
          revoked_reason?: string | null
          user_id: string
          x25519_pubkey: string
        }
        Update: {
          app_version?: string | null
          created_at?: string
          device_id?: string
          display_name?: string
          ed25519_pubkey?: string
          last_ip?: unknown
          last_seen_at?: string
          last_user_agent?: string | null
          os_version?: string | null
          platform?: string
          revoked_at?: string | null
          revoked_reason?: string | null
          user_id?: string
          x25519_pubkey?: string
        }
        Relationships: []
      }
      pairing_offers: {
        Row: {
          consumed_at: string | null
          created_at: string
          expires_at: string
          issuing_device_id: string
          token: string
          user_id: string
        }
        Insert: {
          consumed_at?: string | null
          created_at?: string
          expires_at?: string
          issuing_device_id: string
          token: string
          user_id: string
        }
        Update: {
          consumed_at?: string | null
          created_at?: string
          expires_at?: string
          issuing_device_id?: string
          token?: string
          user_id?: string
        }
        Relationships: []
      }
      waitlist: {
        Row: {
          created_at: string
          email: string
          id: string
          position: number
          referral_code: string
          referral_count: number
          referred_by: string | null
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          position?: never
          referral_code: string
          referral_count?: number
          referred_by?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          position?: never
          referral_code?: string
          referral_count?: number
          referred_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'waitlist_referred_by_fk'
            columns: ['referred_by']
            isOneToOne: false
            referencedRelation: 'waitlist'
            referencedColumns: ['referral_code']
          },
        ]
      }
      waitlist_trending_radar: {
        Row: {
          created_at: string
          email: string
          id: string
          position: number
          source: string
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          position?: never
          source?: string
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          position?: never
          source?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      claim_pairing: {
        Args: {
          p_app_version?: string
          p_device_id: string
          p_display_name: string
          p_ed25519_pubkey: string
          p_os_version?: string
          p_platform: string
          p_token: string
          p_user_id: string
          p_x25519_pubkey: string
        }
        Returns: undefined
      }
      increment_referral_count: {
        Args: { ref_code: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
