// This file is auto-generated by `supabase gen types typescript`.
// DO NOT EDIT MANUALLY. Re-run the codegen command after schema changes:
//   supabase gen types typescript --project-id $SUPABASE_DEV_PROJECT_REF > packages/shared/src/types/supabase.generated.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      devices: {
        Row: {
          device_id: string
          user_id: string
          ed25519_pubkey: string
          x25519_pubkey: string
          platform: string
          display_name: string
          app_version: string | null
          os_version: string | null
          created_at: string
          last_seen_at: string
          revoked_at: string | null
          revoked_reason: string | null
          last_ip: string | null
          last_user_agent: string | null
        }
        Insert: {
          device_id: string
          user_id: string
          ed25519_pubkey: string
          x25519_pubkey: string
          platform: string
          display_name: string
          app_version?: string | null
          os_version?: string | null
          created_at?: string
          last_seen_at?: string
          revoked_at?: string | null
          revoked_reason?: string | null
          last_ip?: string | null
          last_user_agent?: string | null
        }
        Update: {
          device_id?: string
          user_id?: string
          ed25519_pubkey?: string
          x25519_pubkey?: string
          platform?: string
          display_name?: string
          app_version?: string | null
          os_version?: string | null
          created_at?: string
          last_seen_at?: string
          revoked_at?: string | null
          revoked_reason?: string | null
          last_ip?: string | null
          last_user_agent?: string | null
        }
        Relationships: []
      }
      device_events: {
        Row: {
          id: number
          device_id: string
          user_id: string
          event: string
          metadata: Json
          occurred_at: string
        }
        Insert: {
          id?: number
          device_id: string
          user_id: string
          event: string
          metadata?: Json
          occurred_at?: string
        }
        Update: {
          id?: number
          device_id?: string
          user_id?: string
          event?: string
          metadata?: Json
          occurred_at?: string
        }
        Relationships: []
      }
      pairing_offers: {
        Row: {
          token: string
          user_id: string
          issuing_device_id: string
          created_at: string
          expires_at: string
          consumed_at: string | null
        }
        Insert: {
          token: string
          user_id: string
          issuing_device_id: string
          created_at?: string
          expires_at?: string
          consumed_at?: string | null
        }
        Update: {
          token?: string
          user_id?: string
          issuing_device_id?: string
          created_at?: string
          expires_at?: string
          consumed_at?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      claim_pairing: {
        Args: {
          p_token: string
          p_device_id: string
          p_user_id: string
          p_ed25519_pubkey: string
          p_x25519_pubkey: string
          p_platform: string
          p_display_name: string
          p_app_version?: string
          p_os_version?: string
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
