//! Route handlers for coaching rules CRUD operations.

use axum::{
    extract::{Path, State},
    Json,
};
use std::path::PathBuf;
use std::sync::Arc;

use crate::{
    error::{ApiError, ApiResult},
    state::AppState,
};

use super::types::{ApplyRuleRequest, CoachingRule, ListRulesResponse, RemoveRuleResponse};
use super::MAX_RULES;

// ============================================================================
// Validation
// ============================================================================

/// Validate a pattern ID: non-empty, max 10 chars, starts with alpha,
/// only alphanumeric and hyphens.
pub(crate) fn is_valid_pattern_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 10
        && id.starts_with(|c: char| c.is_ascii_alphabetic())
        && id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
}

/// Map an impact score (0.0-1.0) to a confidence label.
fn confidence_label(impact: f64) -> &'static str {
    if impact >= 0.7 {
        "high confidence"
    } else if impact >= 0.4 {
        "moderate confidence"
    } else {
        "low confidence"
    }
}

// ============================================================================
// Handlers
// ============================================================================

/// GET /api/coaching/rules -- List all coaching rules from the rules directory.
#[utoipa::path(get, path = "/api/coaching/rules", tag = "coaching",
    responses(
        (status = 200, description = "All coaching rules from the rules directory", body = crate::routes::coaching::ListRulesResponse),
    )
)]
pub async fn list_rules(State(state): State<Arc<AppState>>) -> ApiResult<Json<ListRulesResponse>> {
    let rules = read_all_rules(&state.rules_dir);
    let count = rules.len();
    Ok(Json(ListRulesResponse {
        rules,
        count,
        max_rules: MAX_RULES,
    }))
}

/// POST /api/coaching/rules -- Create a new coaching rule file.
#[utoipa::path(post, path = "/api/coaching/rules", tag = "coaching",
    request_body = ApplyRuleRequest,
    responses(
        (status = 200, description = "Coaching rule created or updated", body = crate::routes::coaching::CoachingRule),
        (status = 409, description = "Rule budget exceeded (max 8 rules)"),
    )
)]
pub async fn apply_rule(
    State(state): State<Arc<AppState>>,
    Json(req): Json<ApplyRuleRequest>,
) -> ApiResult<Json<CoachingRule>> {
    // Validate pattern ID
    if !is_valid_pattern_id(&req.pattern_id) {
        return Err(ApiError::BadRequest("Invalid pattern ID".to_string()));
    }

    // Check budget (only count existing rules, excluding the one we might overwrite)
    let existing_rules = read_all_rules(&state.rules_dir);
    let is_overwrite = existing_rules.iter().any(|r| r.id == req.pattern_id);
    if !is_overwrite && existing_rules.len() >= MAX_RULES {
        return Err(ApiError::Conflict(
            "Maximum 8 coaching rules. Remove one first.".to_string(),
        ));
    }

    // Ensure directory exists
    std::fs::create_dir_all(&state.rules_dir).map_err(|e| {
        tracing::error!(path = %state.rules_dir.display(), error = %e, "Failed to create rules directory");
        ApiError::Internal(format!("Failed to create rules directory: {}", e))
    })?;

    // Build file content
    let date = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let confidence = confidence_label(req.impact_score);
    let impact_pct = (req.impact_score * 100.0).round() as i64;
    let content = format!(
        "---\n\
         # Auto-generated by claude-view coaching engine\n\
         # Pattern: {} \u{2014} {}\n\
         # Applied: {}\n\
         # Impact: {}% ({}, {} sessions)\n\
         ---\n\
         \n\
         {}\n",
        req.pattern_id,
        req.title,
        date,
        impact_pct,
        confidence,
        req.sample_size,
        req.recommendation,
    );

    // Write file
    let file_path = state
        .rules_dir
        .join(format!("coaching-{}.md", req.pattern_id));
    std::fs::write(&file_path, &content).map_err(|e| {
        tracing::error!(path = %file_path.display(), error = %e, "Failed to write coaching rule file");
        ApiError::Internal(format!("Failed to write rule file: {}", e))
    })?;

    tracing::info!(
        pattern_id = %req.pattern_id,
        title = %req.title,
        file = %file_path.display(),
        "Coaching rule applied"
    );

    Ok(Json(CoachingRule {
        id: req.pattern_id.clone(),
        pattern_id: req.pattern_id,
        title: req.title,
        body: req.recommendation,
        scope: req.scope,
        applied_at: date,
        file_path: file_path.display().to_string(),
    }))
}

/// DELETE /api/coaching/rules/{id} -- Remove a coaching rule file.
#[utoipa::path(delete, path = "/api/coaching/rules/{id}", tag = "coaching",
    params(("id" = String, Path, description = "Coaching rule pattern ID")),
    responses(
        (status = 200, description = "Coaching rule removed", body = crate::routes::coaching::RemoveRuleResponse),
        (status = 400, description = "Rule not found or invalid ID"),
    )
)]
pub async fn remove_rule(
    State(state): State<Arc<AppState>>,
    Path(id): Path<String>,
) -> ApiResult<Json<RemoveRuleResponse>> {
    // Validate the ID to prevent path traversal
    if !is_valid_pattern_id(&id) {
        return Err(ApiError::BadRequest("Invalid pattern ID".to_string()));
    }

    let file_path = state.rules_dir.join(format!("coaching-{}.md", id));

    if !file_path.exists() {
        return Err(ApiError::BadRequest(format!("Rule not found: {}", id)));
    }

    std::fs::remove_file(&file_path).map_err(|e| {
        tracing::error!(path = %file_path.display(), error = %e, "Failed to remove coaching rule file");
        ApiError::Internal(format!("Failed to remove rule file: {}", e))
    })?;

    tracing::info!(pattern_id = %id, file = %file_path.display(), "Coaching rule removed");

    Ok(Json(RemoveRuleResponse { removed: true, id }))
}

// ============================================================================
// File Parsing
// ============================================================================

/// Read all coaching rule files from the rules directory.
fn read_all_rules(rules_dir: &PathBuf) -> Vec<CoachingRule> {
    if !rules_dir.exists() {
        return Vec::new();
    }

    let entries = match std::fs::read_dir(rules_dir) {
        Ok(entries) => entries,
        Err(e) => {
            tracing::warn!(path = %rules_dir.display(), error = %e, "Failed to read rules directory");
            return Vec::new();
        }
    };

    let mut rules: Vec<CoachingRule> = entries
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry
                .file_name()
                .to_str()
                .map(|name| name.starts_with("coaching-") && name.ends_with(".md"))
                .unwrap_or(false)
        })
        .filter_map(|entry| parse_rule_file(&entry.path()))
        .collect();

    // Sort by ID for stable ordering
    rules.sort_by(|a, b| a.id.cmp(&b.id));
    rules
}

/// Parse a single coaching rule Markdown file into a `CoachingRule`.
fn parse_rule_file(path: &std::path::Path) -> Option<CoachingRule> {
    let content = std::fs::read_to_string(path).ok()?;
    let filename = path.file_stem()?.to_str()?;
    let id = filename.strip_prefix("coaching-")?;

    let mut title = String::new();
    let mut applied_at = String::new();
    let mut in_header = false;
    let mut body_lines = Vec::new();

    for line in content.lines() {
        if line.starts_with("---") {
            in_header = !in_header;
            continue;
        }
        if in_header {
            if line.starts_with("# Pattern:") {
                if let Some(rest) = line.split('\u{2014}').nth(1) {
                    title = rest.trim().to_string();
                }
            } else if line.starts_with("# Applied:") {
                applied_at = line.trim_start_matches("# Applied:").trim().to_string();
            }
        } else if !line.is_empty() {
            body_lines.push(line);
        }
    }

    Some(CoachingRule {
        id: id.to_string(),
        pattern_id: id.to_string(),
        title,
        body: body_lines.join(" "),
        scope: "user".to_string(),
        applied_at,
        file_path: path.display().to_string(),
    })
}
