//! Tests for the coaching rules API.

use super::*;
use axum::{
    body::Body,
    http::{Method, Request, StatusCode},
    Router,
};
use claude_view_db::Database;
use tempfile::TempDir;
use tower::ServiceExt;

async fn test_db() -> Database {
    Database::new_in_memory().await.expect("in-memory DB")
}

fn build_app_with_rules_dir(db: Database, rules_dir: std::path::PathBuf) -> Router {
    let mut state = AppState::new(db);
    std::sync::Arc::get_mut(&mut state).unwrap().rules_dir = rules_dir;
    Router::new().nest("/api", router()).with_state(state)
}

async fn do_request(
    app: Router,
    method: Method,
    uri: &str,
    body: Option<&str>,
) -> (StatusCode, String) {
    let mut builder = Request::builder().method(method).uri(uri);
    let body = if let Some(json) = body {
        builder = builder.header("content-type", "application/json");
        Body::from(json.to_string())
    } else {
        Body::empty()
    };
    let response = app.oneshot(builder.body(body).unwrap()).await.unwrap();
    let status = response.status();
    let bytes = axum::body::to_bytes(response.into_body(), usize::MAX)
        .await
        .unwrap();
    (status, String::from_utf8(bytes.to_vec()).unwrap())
}

// --- Validation unit tests ---

#[test]
fn test_valid_pattern_ids() {
    assert!(handlers::is_valid_pattern_id("P1"));
    assert!(handlers::is_valid_pattern_id("abc-def"));
    assert!(handlers::is_valid_pattern_id("a1b2c3d4e5")); // 10 chars, max length
}

#[test]
fn test_invalid_pattern_ids() {
    assert!(!handlers::is_valid_pattern_id(""));
    assert!(!handlers::is_valid_pattern_id("1abc")); // starts with digit
    assert!(!handlers::is_valid_pattern_id("../etc/passwd")); // path traversal
    assert!(!handlers::is_valid_pattern_id("a b")); // space
    assert!(!handlers::is_valid_pattern_id("abcdefghijk")); // 11 chars, too long
    assert!(!handlers::is_valid_pattern_id("a_b")); // underscore not allowed
}

// --- Integration tests ---

#[tokio::test]
async fn test_list_rules_empty() {
    let tmp = TempDir::new().unwrap();
    let rules_dir = tmp.path().join("rules");
    // Don't create the dir -- list should handle missing dir gracefully
    let app = build_app_with_rules_dir(test_db().await, rules_dir);

    let (status, body) = do_request(app, Method::GET, "/api/coaching/rules", None).await;
    assert_eq!(status, StatusCode::OK);

    let resp: ListRulesResponse = serde_json::from_str(&body).unwrap();
    assert_eq!(resp.count, 0);
    assert_eq!(resp.max_rules, 8);
    assert!(resp.rules.is_empty());
}

#[tokio::test]
async fn test_apply_rule_creates_file() {
    let tmp = TempDir::new().unwrap();
    let rules_dir = tmp.path().join("rules");
    let app = build_app_with_rules_dir(test_db().await, rules_dir.clone());

    let payload = serde_json::json!({
        "patternId": "P1",
        "recommendation": "Use focused prompts for better results.",
        "title": "Prompt Clarity",
        "impactScore": 0.75,
        "sampleSize": 42,
        "scope": "user"
    });

    let (status, body) = do_request(
        app,
        Method::POST,
        "/api/coaching/rules",
        Some(&payload.to_string()),
    )
    .await;
    assert_eq!(status, StatusCode::OK);

    let rule: CoachingRule = serde_json::from_str(&body).unwrap();
    assert_eq!(rule.id, "P1");
    assert_eq!(rule.title, "Prompt Clarity");
    assert_eq!(rule.scope, "user");

    // Verify file was actually created on disk
    let file_path = rules_dir.join("coaching-P1.md");
    assert!(file_path.exists(), "Rule file should exist on disk");

    let content = std::fs::read_to_string(&file_path).unwrap();
    assert!(content.contains("Prompt Clarity"));
    assert!(content.contains("75%"));
    assert!(content.contains("high confidence"));
    assert!(content.contains("42 sessions"));
    assert!(content.contains("Use focused prompts"));
}

#[tokio::test]
async fn test_apply_rule_budget_cap() {
    let tmp = TempDir::new().unwrap();
    let rules_dir = tmp.path().join("rules");
    std::fs::create_dir_all(&rules_dir).unwrap();

    // Pre-create 8 rule files to fill the budget
    for i in 0..8 {
        let filename = format!("coaching-R{}.md", i);
        std::fs::write(
            rules_dir.join(&filename),
            format!(
                "---\n# Auto-generated by claude-view coaching engine\n# Pattern: R{} \u{2014} Rule {}\n# Applied: 2026-02-15\n# Impact: 50% (moderate confidence, 20 sessions)\n---\n\nSome rule body.\n",
                i, i
            ),
        )
        .unwrap();
    }

    let app = build_app_with_rules_dir(test_db().await, rules_dir);

    let payload = serde_json::json!({
        "patternId": "P9",
        "recommendation": "This should fail.",
        "title": "Over Budget",
        "impactScore": 0.5,
        "sampleSize": 10,
        "scope": "user"
    });

    let (status, _body) = do_request(
        app,
        Method::POST,
        "/api/coaching/rules",
        Some(&payload.to_string()),
    )
    .await;
    assert_eq!(status, StatusCode::CONFLICT);
}

#[tokio::test]
async fn test_remove_rule_deletes_file() {
    let tmp = TempDir::new().unwrap();
    let rules_dir = tmp.path().join("rules");

    // First, create a rule
    let app = build_app_with_rules_dir(test_db().await, rules_dir.clone());

    let payload = serde_json::json!({
        "patternId": "P1",
        "recommendation": "Test rule body.",
        "title": "Test Rule",
        "impactScore": 0.5,
        "sampleSize": 10,
        "scope": "user"
    });

    let (status, _) = do_request(
        app,
        Method::POST,
        "/api/coaching/rules",
        Some(&payload.to_string()),
    )
    .await;
    assert_eq!(status, StatusCode::OK);

    let file_path = rules_dir.join("coaching-P1.md");
    assert!(file_path.exists());

    // Now delete it
    let app = build_app_with_rules_dir(test_db().await, rules_dir.clone());
    let (status, body) = do_request(app, Method::DELETE, "/api/coaching/rules/P1", None).await;
    assert_eq!(status, StatusCode::OK);

    let resp: RemoveRuleResponse = serde_json::from_str(&body).unwrap();
    assert!(resp.removed);
    assert_eq!(resp.id, "P1");

    // File should be gone
    assert!(!file_path.exists(), "Rule file should be deleted from disk");
}

#[tokio::test]
async fn test_list_rules_reflects_filesystem() {
    let tmp = TempDir::new().unwrap();
    let rules_dir = tmp.path().join("rules");
    std::fs::create_dir_all(&rules_dir).unwrap();

    // Manually write a coaching file (simulating external creation)
    std::fs::write(
        rules_dir.join("coaching-X1.md"),
        "---\n# Auto-generated by claude-view coaching engine\n# Pattern: X1 \u{2014} External Rule\n# Applied: 2026-01-01\n# Impact: 60% (moderate confidence, 15 sessions)\n---\n\nExternal recommendation text.\n",
    )
    .unwrap();

    let app = build_app_with_rules_dir(test_db().await, rules_dir);

    let (status, body) = do_request(app, Method::GET, "/api/coaching/rules", None).await;
    assert_eq!(status, StatusCode::OK);

    let resp: ListRulesResponse = serde_json::from_str(&body).unwrap();
    assert_eq!(resp.count, 1);
    assert_eq!(resp.rules[0].id, "X1");
    assert_eq!(resp.rules[0].title, "External Rule");
    assert_eq!(resp.rules[0].applied_at, "2026-01-01");
    assert!(resp.rules[0].body.contains("External recommendation"));
}

#[tokio::test]
async fn test_apply_rule_idempotent() {
    let tmp = TempDir::new().unwrap();
    let rules_dir = tmp.path().join("rules");

    let payload = serde_json::json!({
        "patternId": "P1",
        "recommendation": "First version.",
        "title": "Test Rule",
        "impactScore": 0.5,
        "sampleSize": 10,
        "scope": "user"
    });

    // Apply once
    let app = build_app_with_rules_dir(test_db().await, rules_dir.clone());
    let (status, _) = do_request(
        app,
        Method::POST,
        "/api/coaching/rules",
        Some(&payload.to_string()),
    )
    .await;
    assert_eq!(status, StatusCode::OK);

    // Apply again with same ID (overwrite)
    let payload2 = serde_json::json!({
        "patternId": "P1",
        "recommendation": "Updated version.",
        "title": "Test Rule v2",
        "impactScore": 0.8,
        "sampleSize": 20,
        "scope": "user"
    });

    let app = build_app_with_rules_dir(test_db().await, rules_dir.clone());
    let (status, _) = do_request(
        app,
        Method::POST,
        "/api/coaching/rules",
        Some(&payload2.to_string()),
    )
    .await;
    assert_eq!(status, StatusCode::OK);

    // Verify only one file exists
    let files: Vec<_> = std::fs::read_dir(&rules_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .collect();
    assert_eq!(files.len(), 1, "Should have exactly 1 file, not 2");

    // Verify content is the updated version
    let content = std::fs::read_to_string(rules_dir.join("coaching-P1.md")).unwrap();
    assert!(content.contains("Updated version."));
}

#[tokio::test]
async fn test_invalid_pattern_id_rejected() {
    let tmp = TempDir::new().unwrap();
    let rules_dir = tmp.path().join("rules");
    let app = build_app_with_rules_dir(test_db().await, rules_dir);

    let payload = serde_json::json!({
        "patternId": "../etc/passwd",
        "recommendation": "Malicious.",
        "title": "Evil",
        "impactScore": 0.5,
        "sampleSize": 1,
        "scope": "user"
    });

    let (status, _) = do_request(
        app,
        Method::POST,
        "/api/coaching/rules",
        Some(&payload.to_string()),
    )
    .await;
    assert_eq!(status, StatusCode::BAD_REQUEST);
}

#[tokio::test]
async fn test_remove_nonexistent_rule() {
    let tmp = TempDir::new().unwrap();
    let rules_dir = tmp.path().join("rules");
    std::fs::create_dir_all(&rules_dir).unwrap();

    let app = build_app_with_rules_dir(test_db().await, rules_dir);

    let (status, _) = do_request(app, Method::DELETE, "/api/coaching/rules/nope", None).await;
    assert_eq!(status, StatusCode::BAD_REQUEST);
}
