use vibe_recall_core::{SessionInfo, ToolCounts};

fn main() {
    let session = SessionInfo {
        id: "test".to_string(),
        project: "test".to_string(),
        project_path: "/test".to_string(),
        file_path: "/test/session.jsonl".to_string(),
        modified_at: 1769482232,
        size_bytes: 100,
        preview: "Test".to_string(),
        last_message: "Test".to_string(),
        files_touched: vec![],
        skills_used: vec![],
        tool_counts: ToolCounts::default(),
        message_count: 1,
        turn_count: 1,
        summary: None,
        git_branch: None,
        is_sidechain: false,
        deep_indexed: false,
        total_input_tokens: None,
        total_output_tokens: None,
        total_cache_read_tokens: None,
        total_cache_creation_tokens: None,
        turn_count_api: None,
        primary_model: None,
        // Phase 3: Atomic unit metrics
        user_prompt_count: 0,
        api_call_count: 0,
        tool_call_count: 0,
        files_read: vec![],
        files_edited: vec![],
        files_read_count: 0,
        files_edited_count: 0,
        reedited_files_count: 0,
        duration_seconds: 0,
        commit_count: 0,
        thinking_block_count: 0,
        turn_duration_avg_ms: None,
        turn_duration_max_ms: None,
        api_error_count: 0,
        compaction_count: 0,
        agent_spawn_count: 0,
        bash_progress_count: 0,
        hook_progress_count: 0,
        mcp_progress_count: 0,

        parse_version: 0,
        lines_added: 0,
        lines_removed: 0,
        loc_source: 0,
        // Theme 4: Classification
        category_l1: None,
        category_l2: None,
        category_l3: None,
        category_confidence: None,
        category_source: None,
        classified_at: None,
        prompt_word_count: None,
        correction_count: 0,
        same_file_edit_count: 0,
    };

    let json = serde_json::to_string_pretty(&session).unwrap();
    println!("{}", json);
}
