import { useState } from 'react'
import { cn } from '../../lib/utils'
import { FileText, Download, Eye, X, Check, Copy } from 'lucide-react'
import type { ReportSummary } from '../../types/generated/ReportSummary'

interface MonthlyReportGeneratorProps {
  reportSummary: ReportSummary
  className?: string
}

/**
 * Generate a plain-text report suitable for download or clipboard.
 */
function generateReportText(report: ReportSummary): string {
  const lines = [
    '='.repeat(60),
    'Claude Code Monthly Report',
    report.month,
    '='.repeat(60),
    '',
    'Summary',
    '-'.repeat(40),
    `Sessions:      ${report.sessionCount}`,
    `Lines Added:   +${report.linesAdded.toLocaleString()}`,
    `Lines Removed: -${report.linesRemoved.toLocaleString()}`,
    `Commits:       ${report.commitCount}`,
    `Est. Cost:     $${report.estimatedCost.toFixed(2)}`,
    '',
    'Top Achievements',
    '-'.repeat(40),
    ...report.topWins.map((win) => `  [ok] ${win}`),
    '',
    'Focus Areas',
    '-'.repeat(40),
    ...report.focusAreas.map((area) => `  ->  ${area}`),
    '',
    '-'.repeat(60),
    `Generated by claude-view on ${new Date().toLocaleDateString()}`,
  ]
  return lines.join('\n')
}

export function MonthlyReportGenerator({
  reportSummary,
  className,
}: MonthlyReportGeneratorProps) {
  const [showPreview, setShowPreview] = useState(false)
  const [copied, setCopied] = useState(false)

  const handleDownload = () => {
    const text = generateReportText(reportSummary)
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `claude-code-report-${reportSummary.month.toLowerCase().replace(/\s+/g, '-')}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleCopy = async () => {
    const text = generateReportText(reportSummary)
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback for browsers without clipboard API
      const textarea = document.createElement('textarea')
      textarea.value = text
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div
      className={cn(
        'bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-700 p-6',
        className
      )}
    >
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Monthly Report</h3>
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors cursor-pointer"
        >
          <Download className="w-4 h-4" />
          Download Report
        </button>
      </div>

      {/* Summary card */}
      <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4 mb-4">
        <h4 className="text-base font-semibold text-gray-900 dark:text-gray-100 mb-3">
          {reportSummary.month} Summary
        </h4>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
          <div className="text-center">
            <p className="text-2xl font-semibold text-blue-600 dark:text-blue-400 font-mono">
              {reportSummary.sessionCount}
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-400">Sessions</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-semibold text-green-600 dark:text-green-400 font-mono">
              +{reportSummary.linesAdded.toLocaleString()}
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-400">Lines</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-semibold text-purple-600 dark:text-purple-400 font-mono">
              {reportSummary.commitCount}
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-400">Commits</p>
          </div>
          <div className="text-center">
            <p className="text-2xl font-semibold text-gray-600 dark:text-gray-400 font-mono">
              ${reportSummary.estimatedCost.toFixed(2)}
            </p>
            <p className="text-xs text-gray-500 dark:text-gray-400">Est. Cost</p>
          </div>
        </div>

        {/* Top wins */}
        {reportSummary.topWins.length > 0 && (
          <div className="mb-3">
            <h5 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Top Wins:
            </h5>
            <ul className="space-y-1">
              {reportSummary.topWins.map((win, i) => (
                <li
                  key={i}
                  className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400"
                >
                  <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" />
                  {win}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Focus areas */}
        {reportSummary.focusAreas.length > 0 && (
          <div>
            <h5 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Focus Areas:
            </h5>
            <ul className="space-y-1">
              {reportSummary.focusAreas.map((area, i) => (
                <li
                  key={i}
                  className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400"
                >
                  <span className="text-gray-400 mt-0.5 shrink-0">-&gt;</span>
                  {area}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Action buttons */}
      <div className="flex justify-end gap-2">
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors cursor-pointer"
        >
          {copied ? (
            <>
              <Check className="w-4 h-4 text-green-500" />
              Copied
            </>
          ) : (
            <>
              <Copy className="w-4 h-4" />
              Copy to Clipboard
            </>
          )}
        </button>
        <button
          onClick={() => setShowPreview(true)}
          className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors cursor-pointer"
        >
          <Eye className="w-4 h-4" />
          Preview
        </button>
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg transition-colors cursor-pointer"
        >
          <FileText className="w-4 h-4" />
          Download
        </button>
      </div>

      {/* Preview modal */}
      {showPreview && (
        <ReportPreviewModal
          reportSummary={reportSummary}
          onClose={() => setShowPreview(false)}
          onDownload={handleDownload}
        />
      )}
    </div>
  )
}

// ============================================================================
// Report Preview Modal
// ============================================================================

interface ReportPreviewModalProps {
  reportSummary: ReportSummary
  onClose: () => void
  onDownload: () => void
}

function ReportPreviewModal({ reportSummary, onClose, onDownload }: ReportPreviewModalProps) {
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose()
      }}
      role="dialog"
      aria-modal="true"
      aria-label="Report preview"
    >
      <div className="bg-white dark:bg-gray-900 rounded-xl shadow-2xl max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            Report Preview
          </h2>
          <button
            onClick={onClose}
            className="p-1 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 cursor-pointer"
            aria-label="Close preview"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Report content */}
        <div className="p-6">
          <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100 mb-2">
            Claude Code Monthly Report
          </h3>
          <p className="text-gray-500 dark:text-gray-400 mb-6">{reportSummary.month}</p>

          {/* Stats grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
            <div className="text-center">
              <p className="text-2xl font-semibold text-blue-600 dark:text-blue-400 font-mono">
                {reportSummary.sessionCount}
              </p>
              <p className="text-xs text-gray-500 dark:text-gray-400">Sessions</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-semibold text-green-600 dark:text-green-400 font-mono">
                +{reportSummary.linesAdded.toLocaleString()}
              </p>
              <p className="text-xs text-gray-500 dark:text-gray-400">Lines Added</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-semibold text-purple-600 dark:text-purple-400 font-mono">
                {reportSummary.commitCount}
              </p>
              <p className="text-xs text-gray-500 dark:text-gray-400">Commits</p>
            </div>
            <div className="text-center">
              <p className="text-2xl font-semibold text-gray-600 dark:text-gray-400 font-mono">
                ${reportSummary.estimatedCost.toFixed(2)}
              </p>
              <p className="text-xs text-gray-500 dark:text-gray-400">Est. Cost</p>
            </div>
          </div>

          {/* Top wins */}
          {reportSummary.topWins.length > 0 && (
            <div className="mb-4">
              <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Top Achievements
              </h4>
              <ul className="space-y-1">
                {reportSummary.topWins.map((win, i) => (
                  <li
                    key={i}
                    className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400"
                  >
                    <Check className="w-4 h-4 text-green-500 mt-0.5 shrink-0" />
                    {win}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Focus areas */}
          {reportSummary.focusAreas.length > 0 && (
            <div>
              <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Focus Areas
              </h4>
              <ul className="space-y-1">
                {reportSummary.focusAreas.map((area, i) => (
                  <li
                    key={i}
                    className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400"
                  >
                    <span className="text-gray-400 mt-0.5 shrink-0">-&gt;</span>
                    {area}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-2 p-4 border-t border-gray-200 dark:border-gray-700">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-lg cursor-pointer"
          >
            Close
          </button>
          <button
            onClick={onDownload}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg cursor-pointer"
          >
            <Download className="w-4 h-4" />
            Download Report
          </button>
        </div>
      </div>
    </div>
  )
}
