// crates/server/src/routes/contributions/mod.rs
//! Contributions API endpoints for Theme 3.
//!
//! This module provides:
//! - `GET /api/contributions` - Main contributions page data
//! - `GET /api/contributions/sessions/:id` - Session contribution detail
//! - `GET /api/contributions/branches/:name/sessions` - Sessions for a branch
//!
//! ## Caching
//!
//! Responses include Cache-Control headers based on the time range:
//! - Today: 1 minute (real-time data)
//! - Week: 5 minutes
//! - Month: 15 minutes
//! - 90 days / All: 30 minutes

mod handlers;
mod helpers;
mod scope_meta;
mod types;

use std::sync::Arc;

use axum::{routing::get, Router};

use crate::state::AppState;

// Re-export handler functions (used in openapi.rs path annotations)
pub use handlers::{get_branch_sessions, get_contributions, get_session_contribution};

// Re-export utoipa __path_* types (generated by #[utoipa::path] on handlers)
pub use handlers::{
    __path_get_branch_sessions, __path_get_contributions, __path_get_session_contribution,
};

// Re-export response/query types (used in openapi.rs schema registration)
pub use types::{
    BranchSessionsResponse, ContributionWarning, ContributionsResponse, EffectivenessMetrics,
    EfficiencyMetrics, FluencyMetrics, OutputMetrics, OverviewMetrics, SessionContributionResponse,
};

/// Create the contributions routes router.
pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route("/contributions", get(get_contributions))
        .route(
            "/contributions/sessions/{id}",
            get(get_session_contribution),
        )
        .route(
            "/contributions/branches/{name}/sessions",
            get(get_branch_sessions),
        )
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::types::*;
    use axum::{
        body::Body,
        http::{HeaderMap, Request, StatusCode},
    };
    use claude_view_core::{AnalyticsScopeMeta, AnalyticsSessionBreakdown};
    use claude_view_db::{Database, LearningCurve};
    use sqlx::Executor;
    use tower::ServiceExt;

    async fn test_db() -> Database {
        Database::new_in_memory().await.expect("in-memory DB")
    }

    fn build_app(db: Database) -> axum::Router {
        crate::create_app(db)
    }

    async fn do_get(app: axum::Router, uri: &str) -> (StatusCode, String, HeaderMap) {
        let response = app
            .oneshot(Request::builder().uri(uri).body(Body::empty()).unwrap())
            .await
            .unwrap();
        let status = response.status();
        let headers = response.headers().clone();
        let body = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .unwrap();
        (status, String::from_utf8(body.to_vec()).unwrap(), headers)
    }

    async fn insert_contribution_session(
        db: &Database,
        id: &str,
        last_message_at: i64,
        is_sidechain: bool,
        branch: Option<&str>,
    ) {
        // Insert into sessions (legacy table for backwards compat)
        db.pool()
            .execute(
                sqlx::query(
                    r#"
                    INSERT INTO sessions (
                        id, project_id, file_path, preview, project_path, project_display_name,
                        duration_seconds, files_edited_count, reedited_files_count, files_read_count,
                        user_prompt_count, api_call_count, tool_call_count, commit_count, turn_count,
                        last_message_at, size_bytes, last_message, files_touched, skills_used,
                        files_read, files_edited, ai_lines_added, ai_lines_removed,
                        is_sidechain, git_branch
                    )
                    VALUES (
                        ?1, 'proj', '/tmp/' || ?1 || '.jsonl', 'test', '/tmp', 'Project',
                        120, 2, 0, 1,
                        3, 5, 7, 0, 4,
                        ?2, 1024, 'last', '[]', '[]',
                        '[]', '[]', 10, 2,
                        ?3, ?4
                    )
                    "#,
                )
                .bind(id)
                .bind(last_message_at)
                .bind(is_sidechain)
                .bind(branch),
            )
            .await
            .unwrap();

        // Also insert into session_stats (primary read table for Phase 7.c queries)
        db.pool()
            .execute(
                sqlx::query(
                    r#"
                    INSERT INTO session_stats (
                        session_id, source_content_hash, source_size, parser_version,
                        stats_version, indexed_at, last_message_at, is_sidechain,
                        git_branch
                    )
                    VALUES (
                        ?1, X'00', 1024, 1, 3, 0, ?2, ?3, ?4
                    )
                    "#,
                )
                .bind(id)
                .bind(last_message_at)
                .bind(is_sidechain as i64)
                .bind(branch),
            )
            .await
            .unwrap();
    }

    #[tokio::test]
    async fn test_get_contributions_empty_db() {
        let db = test_db().await;
        let app = build_app(db);
        let (status, body, headers) = do_get(app, "/api/contributions").await;

        assert_eq!(status, StatusCode::OK);

        // Check response structure
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert!(json["overview"].is_object());
        assert!(json["overview"]["fluency"].is_object());
        assert!(json["overview"]["output"].is_object());
        assert!(json["overview"]["effectiveness"].is_object());
        assert!(json["trend"].is_array());
        assert!(json["efficiency"].is_object());
        assert!(json["byBranch"].is_array());

        // Empty responses should not be cached (server may still be generating snapshots)
        let cache_control = headers.get("cache-control").unwrap().to_str().unwrap();
        assert!(cache_control.contains("no-cache"));
    }

    #[tokio::test]
    async fn test_get_contributions_includes_data_scope_meta() {
        let db = test_db().await;
        let app = build_app(db);
        let (status, body, _) = do_get(app, "/api/contributions?range=all").await;

        assert_eq!(status, StatusCode::OK);
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(
            json["meta"]["dataScope"]["sessions"],
            "primary_sessions_only"
        );
        assert_eq!(
            json["meta"]["dataScope"]["workload"],
            "primary_plus_subagent_work"
        );
    }

    #[tokio::test]
    async fn test_contributions_includes_session_breakdown_meta() {
        let db = test_db().await;
        let now = chrono::Utc::now().timestamp();
        insert_contribution_session(&db, "cont-primary", now - 60, false, Some("main")).await;
        insert_contribution_session(&db, "cont-sidechain", now - 30, true, Some("main")).await;

        let app = build_app(db);
        let (status, body, _) = do_get(app, "/api/contributions?range=all").await;

        assert_eq!(status, StatusCode::OK);
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(json["meta"]["sessionBreakdown"]["primarySessions"], 1);
        assert_eq!(json["meta"]["sessionBreakdown"]["sidechainSessions"], 1);
        assert_eq!(json["meta"]["sessionBreakdown"]["otherSessions"], 0);
        assert_eq!(json["meta"]["sessionBreakdown"]["totalObservedSessions"], 2);
    }

    #[tokio::test]
    async fn test_get_contributions_with_range() {
        let db = test_db().await;
        let app = build_app(db);
        let (status, _, headers) = do_get(app, "/api/contributions?range=today").await;

        assert_eq!(status, StatusCode::OK);

        // Empty DB: should get no-cache (not range-based caching)
        let cache_control = headers.get("cache-control").unwrap().to_str().unwrap();
        assert!(cache_control.contains("no-cache"));
    }

    #[tokio::test]
    async fn test_get_contributions_week_cache() {
        let db = test_db().await;
        let app = build_app(db);
        let (status, _, headers) = do_get(app, "/api/contributions?range=week").await;

        assert_eq!(status, StatusCode::OK);

        // Empty DB: should get no-cache (not range-based caching)
        let cache_control = headers.get("cache-control").unwrap().to_str().unwrap();
        assert!(cache_control.contains("no-cache"));
    }

    #[tokio::test]
    async fn test_get_contributions_custom_range() {
        let db = test_db().await;
        let app = build_app(db);
        let (status, body, _) = do_get(
            app,
            "/api/contributions?range=custom&from=2026-01-01&to=2026-02-01",
        )
        .await;

        assert_eq!(status, StatusCode::OK);

        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert!(json["overview"].is_object());
    }

    #[tokio::test]
    async fn test_get_session_contribution_includes_data_scope_meta() {
        let db = test_db().await;
        let now = chrono::Utc::now().timestamp();
        insert_contribution_session(
            &db,
            "session-meta-primary",
            now - 10,
            false,
            Some("feature/meta"),
        )
        .await;

        let app = build_app(db);
        let (status, body, _) =
            do_get(app, "/api/contributions/sessions/session-meta-primary").await;

        assert_eq!(status, StatusCode::OK);
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(
            json["meta"]["dataScope"]["sessions"],
            "primary_sessions_only"
        );
        assert_eq!(
            json["meta"]["dataScope"]["workload"],
            "primary_plus_subagent_work"
        );
        assert_eq!(json["meta"]["sessionBreakdown"]["primarySessions"], 1);
        assert_eq!(json["meta"]["sessionBreakdown"]["sidechainSessions"], 0);
        assert_eq!(json["meta"]["sessionBreakdown"]["otherSessions"], 0);
        assert_eq!(json["meta"]["sessionBreakdown"]["totalObservedSessions"], 1);
    }

    #[tokio::test]
    async fn test_get_branch_sessions_includes_data_scope_meta() {
        let db = test_db().await;
        let now = chrono::Utc::now().timestamp();
        insert_contribution_session(
            &db,
            "branch-meta-primary",
            now - 60,
            false,
            Some("feature/meta"),
        )
        .await;
        insert_contribution_session(
            &db,
            "branch-meta-sidechain",
            now - 30,
            true,
            Some("feature/meta"),
        )
        .await;

        let app = build_app(db);
        let (status, body, _) = do_get(
            app,
            "/api/contributions/branches/feature%2Fmeta/sessions?range=all",
        )
        .await;

        assert_eq!(status, StatusCode::OK);
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(
            json["meta"]["dataScope"]["sessions"],
            "primary_sessions_only"
        );
        assert_eq!(
            json["meta"]["dataScope"]["workload"],
            "primary_plus_subagent_work"
        );
        assert_eq!(json["meta"]["sessionBreakdown"]["primarySessions"], 1);
        assert_eq!(json["meta"]["sessionBreakdown"]["sidechainSessions"], 1);
        assert_eq!(json["meta"]["sessionBreakdown"]["otherSessions"], 0);
        assert_eq!(json["meta"]["sessionBreakdown"]["totalObservedSessions"], 2);
    }

    #[tokio::test]
    async fn test_get_session_contribution_not_found() {
        let db = test_db().await;
        let app = build_app(db);
        let (status, body, _) =
            do_get(app, "/api/contributions/sessions/nonexistent-session").await;

        assert_eq!(status, StatusCode::NOT_FOUND);

        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert!(json["error"].is_string());
    }

    #[tokio::test]
    async fn test_contributions_response_serialization() {
        let response = ContributionsResponse {
            overview: OverviewMetrics {
                fluency: FluencyMetrics {
                    sessions: 10,
                    prompts_per_session: 5.5,
                    trend: Some(15.0),
                    insight: crate::insights::Insight::info("Test"),
                },
                output: OutputMetrics {
                    lines_added: 500,
                    lines_removed: 100,
                    files_count: 12,
                    commits_count: 5,
                    insight: crate::insights::Insight::info("Test"),
                },
                effectiveness: EffectivenessMetrics {
                    commit_rate: Some(0.8),
                    reedit_rate: Some(0.15),
                    insight: crate::insights::Insight::success("Excellent"),
                },
            },
            trend: vec![],
            efficiency: EfficiencyMetrics {
                total_cost: 2.50,
                total_lines: 600,
                priced_lines: 540,
                cost_per_line: Some(0.004),
                cost_per_commit: Some(0.50),
                cost_trend: vec![0.5, 0.4, 0.3],
                has_unpriced_usage: true,
                priced_model_count: 3,
                unpriced_model_count: 1,
                unpriced_input_tokens: 1000,
                unpriced_output_tokens: 500,
                unpriced_cache_read_tokens: 100,
                unpriced_cache_creation_tokens: 50,
                priced_token_coverage: 0.9,
                cost_scope: "priced_models_only_partial".to_string(),
                insight: crate::insights::Insight::info("Good"),
            },
            by_model: vec![],
            learning_curve: LearningCurve {
                periods: vec![],
                current_avg: 0.2,
                improvement: 10.0,
                insight: "Steady improvement".to_string(),
            },
            by_branch: vec![],
            by_skill: vec![],
            skill_insight: "Skill insight".to_string(),
            uncommitted: vec![],
            uncommitted_insight: "No uncommitted work".to_string(),
            warnings: vec![],
            meta: AnalyticsScopeMeta::new(AnalyticsSessionBreakdown::new(10, 2)),
        };

        let json = serde_json::to_string(&response).unwrap();

        // Verify camelCase
        assert!(json.contains("promptsPerSession"));
        assert!(json.contains("linesAdded"));
        assert!(json.contains("commitRate"));
        assert!(json.contains("reeditRate"));
        assert!(json.contains("totalCost"));
        assert!(json.contains("costPerLine"));
        // Verify new fields
        assert!(json.contains("byModel"));
        assert!(json.contains("learningCurve"));
        assert!(json.contains("bySkill"));
        assert!(json.contains("skillInsight"));
        assert!(json.contains("uncommitted"));
        assert!(json.contains("uncommittedInsight"));
    }
}
