//! Classification API routes.
//!
//! - POST /classify              — Trigger classification job
//! - GET  /classify/status       — Get classification status
//! - GET  /classify/stream       — SSE stream of classification progress
//! - POST /classify/cancel       — Cancel running classification
//! - POST /classify/single/:id   — Classify a single session

mod handlers;
mod job;
mod stream;
mod types;

#[cfg(test)]
mod tests;

use std::sync::Arc;

use axum::routing::{get, post};
use axum::Router;

use crate::state::AppState;

// Re-export handlers (used by openapi.rs)
pub use handlers::{
    cancel_classification, classify_single_session, get_classification_status, start_classification,
};

// Re-export SSE handler (used by openapi.rs)
pub use stream::stream_classification;

// Re-export utoipa __path_* types (generated by #[utoipa::path] on handlers)
pub use handlers::{
    __path_cancel_classification, __path_classify_single_session, __path_get_classification_status,
    __path_start_classification,
};
pub use stream::__path_stream_classification;

// Re-export public types (used by openapi.rs schemas)
pub use types::{
    CancelResponse, ClassifyErrorInfo, ClassifyLastRun, ClassifyProgressInfo, ClassifyResponse,
    ClassifySingleResponse, ClassifyStatusResponse,
};

/// Build the classify router.
pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route("/classify", post(start_classification))
        .route(
            "/classify/single/{session_id}",
            post(classify_single_session),
        )
        .route("/classify/status", get(get_classification_status))
        .route("/classify/stream", get(stream_classification))
        .route("/classify/cancel", post(cancel_classification))
}
