//! Dashboard statistics endpoints.

mod ai_generation;
mod dashboard;
mod helpers;
mod types;

#[cfg(test)]
mod tests;

// Re-export all public items that were previously accessible from `stats.rs`.
pub use ai_generation::ai_generation_stats;
pub use dashboard::dashboard_stats;
pub use types::{
    AIGenerationStatsResponse, CurrentPeriodMetrics, DashboardMeta, DashboardQuery,
    DashboardRangesMeta, DashboardTrends, ExtendedDashboardStats, StorageStats,
};

// utoipa __path_* re-exports (generated by #[utoipa::path] in submodules)
#[allow(unused_imports)]
pub use ai_generation::__path_ai_generation_stats;
#[allow(unused_imports)]
pub use dashboard::__path_dashboard_stats;

use std::sync::Arc;

use axum::{routing::get, Router};

use crate::state::AppState;

/// Create the stats routes router.
pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route("/stats/dashboard", get(dashboard_stats))
        .route("/stats/storage", get(storage::storage_stats))
        .route("/stats/ai-generation", get(ai_generation_stats))
}

// Keep the storage handler accessible via `storage::storage_stats` for the router,
// and re-export the handler itself for external callers.
#[allow(unused_imports)]
pub use storage::__path_storage_stats;
pub use storage::storage_stats;
mod storage;
