#!/bin/bash
# scripts/generate-types.sh
# Generate TypeScript type definitions from Rust structs using ts-rs.
#
# ts-rs emits .ts files during `cargo test` for any struct/enum with
# #[derive(TS)] #[ts(export)]. We run only the export_bindings tests
# (auto-generated by ts-rs) to trigger file generation without running
# the full test suite.
#
# Output: packages/shared/src/types/generated/*.ts  (live session types)
#         apps/web/src/types/generated/*.ts          (server route types)
#
# Usage: ./scripts/generate-types.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT_DIR"

echo "Generating TypeScript types from Rust structs..."

# Run only the export_bindings tests with the `codegen` feature enabled.
# Without `--features codegen`, #[ts(export)] is gated off via cfg_attr,
# so normal `cargo test` never touches the generated files.
cargo test -p claude-view-core --features codegen export_bindings -- --nocapture
cargo test -p claude-view-db --features codegen export_bindings -- --nocapture
cargo test -p claude-view-server --features codegen export_bindings -- --nocapture

# Post-process: fix cross-package JsonValue import that ts-rs generates
# ts-rs resolves serde_json::Value to apps/web/... but we use a local shim
AGENT_STATE="packages/shared/src/types/generated/AgentState.ts"
if [ -f "$AGENT_STATE" ]; then
  tmp_file="$(mktemp)"
  sed "s|import type { JsonValue } from .*serde_json/JsonValue.*|import type { JsonValue } from './JsonValue'|" "$AGENT_STATE" >"$tmp_file"
  mv "$tmp_file" "$AGENT_STATE"
fi

# Format + organize imports with Biome so output matches project style and pre-commit hook
# Uses `biome check --write` (not `biome format`) to include organizeImports
# Linting is disabled for generated dirs via biome.json overrides
echo ""
echo "Formatting generated types with Biome..."
bunx biome check --write --no-errors-on-unmatched \
  packages/shared/src/types/generated/ \
  apps/web/src/types/generated/

echo ""
echo "=== Shared types (packages/shared/src/types/generated/) ==="
if ls packages/shared/src/types/generated/*.ts 1>/dev/null 2>&1; then
  ls packages/shared/src/types/generated/*.ts
else
  echo "(no shared .ts files generated)"
fi

echo ""
echo "=== Web types (apps/web/src/types/generated/) ==="
if ls apps/web/src/types/generated/*.ts 1>/dev/null 2>&1; then
  ls apps/web/src/types/generated/*.ts | wc -l | xargs -I{} echo "{} files"
else
  echo "(no web .ts files generated)"
fi
