#!/bin/bash
# scripts/generate-types.sh
# Generate TypeScript type definitions from Rust structs using ts-rs.
#
# ts-rs emits .ts files during `cargo test` for any struct/enum with
# #[derive(TS)] #[ts(export)]. We run only the export_bindings tests
# (auto-generated by ts-rs) to trigger file generation without running
# the full test suite.
#
# Output: packages/shared/src/types/generated/*.ts  (live session types)
#         apps/web/src/types/generated/*.ts          (server route types)
#
# Usage: ./scripts/generate-types.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT_DIR"

echo "Generating TypeScript types from Rust structs..."

# Run only the export_bindings tests with the `codegen` feature enabled.
# Without `--features codegen`, #[ts(export)] is gated off via cfg_attr,
# so normal `cargo test` never touches the generated files.
#
# claude-view-types owns the base shared types — Message/SessionInfo/
# ContentBlock plus the whole ConversationBlock hierarchy (block_types.rs:
# SystemVariant, ImageContent, etc.). ts-rs writes each type's .ts from its
# OWN defining crate's export_bindings test (deps are imported, not
# co-written), so omitting this crate froze Message.ts / SystemVariant.ts /
# ImageContent.ts whenever those types changed. Run it first (base layer).
"$ROOT_DIR/scripts/cq" test -p claude-view-types --features codegen export_bindings -- --nocapture
"$ROOT_DIR/scripts/cq" test -p claude-view-core --features codegen export_bindings -- --nocapture
"$ROOT_DIR/scripts/cq" test -p claude-view-search --features codegen export_bindings -- --nocapture
"$ROOT_DIR/scripts/cq" test -p claude-view-db --features codegen export_bindings -- --nocapture
# claude-view-server-live-state owns HookFields/JsonlFields/LiveSession/AgentState
# etc. (extracted in 37dba7ad). Its ts-rs export_bindings tests live in its own
# test target, so they must be run explicitly — omitting this froze
# HookFields.ts / JsonlFields.ts at their pre-extraction state.
"$ROOT_DIR/scripts/cq" test -p claude-view-server-live-state --features codegen export_bindings -- --nocapture
"$ROOT_DIR/scripts/cq" test -p claude-view-server --features codegen export_bindings -- --nocapture

# Post-process: fix cross-package JsonValue import that ts-rs generates
# ts-rs resolves serde_json::Value to apps/web/... but we use a local shim
AGENT_STATE="packages/shared/src/types/generated/AgentState.ts"
if [ -f "$AGENT_STATE" ]; then
  tmp_file="$(mktemp)"
  sed "s|import type { JsonValue } from .*serde_json/JsonValue.*|import type { JsonValue } from './JsonValue'|" "$AGENT_STATE" >"$tmp_file"
  mv "$tmp_file" "$AGENT_STATE"
fi

# Format + organize imports with Biome so output matches project style and pre-commit hook
# Uses `biome check --write` (not `biome format`) to include organizeImports
# Linting is disabled for generated dirs via biome.json overrides
echo ""
echo "Formatting generated types with Biome..."
bunx biome check --write --no-errors-on-unmatched \
  packages/shared/src/types/generated/ \
  apps/web/src/types/generated/

# Post-process: localize cross-package imports that escape shared's rootDir.
# ts-rs emits absolute-ish `../../../../../apps/web/src/types/generated/X`
# imports for types that are ALSO generated into shared (X exists in both
# trees). Those escape `packages/shared`'s tsconfig rootDir (TS6059).
#
# Root-cause fix (replaces a brittle hand-maintained type-name allowlist that
# silently drifted — it missed PendingInteractionMeta/SessionOwnership):
# for every shared generated file, rewrite any apps/web escape to a local
# `./X` import IFF `packages/shared/src/types/generated/X.ts` exists. Types
# that genuinely live only in apps/web are left untouched.
#
# MUST run AFTER Biome: ts-rs emits DOUBLE-quoted imports, Biome rewrites them
# to single quotes. This regex matches single-quoted imports, so running it
# before Biome silently no-ops (the bug that froze LiveSession.ts's imports
# pointing into apps/web and broke `packages/shared` typecheck).
SHARED_GEN="packages/shared/src/types/generated"
if [ -d "$SHARED_GEN" ]; then
  for f in "$SHARED_GEN"/*.ts; do
    [ -f "$f" ] || continue
    perl -i -pe '
      s{from '\''[^'\'']*?/apps/web/src/types/generated/(\w+)'\''}{
        -f "'"$SHARED_GEN"'/$1.ts" ? "from '\''./$1'\''" : $&
      }ge;
    ' "$f"
  done
fi

echo ""
echo "=== Shared types (packages/shared/src/types/generated/) ==="
if ls packages/shared/src/types/generated/*.ts 1>/dev/null 2>&1; then
  ls packages/shared/src/types/generated/*.ts
else
  echo "(no shared .ts files generated)"
fi

echo ""
echo "=== Web types (apps/web/src/types/generated/) ==="
if ls apps/web/src/types/generated/*.ts 1>/dev/null 2>&1; then
  ls apps/web/src/types/generated/*.ts | wc -l | xargs -I{} echo "{} files"
else
  echo "(no web .ts files generated)"
fi
