#!/bin/bash
# scripts/generate-types.sh
# Generate TypeScript type definitions from Rust structs using ts-rs.
#
# ts-rs emits .ts files during `cargo test` for any struct/enum with
# #[derive(TS)] #[ts(export)]. We run only the export_bindings tests
# (auto-generated by ts-rs) to trigger file generation without running
# the full test suite.
#
# Output: packages/shared/src/types/generated/*.ts  (live session types)
#         apps/web/src/types/generated/*.ts          (server route types)
#
# Usage: ./scripts/generate-types.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT_DIR"

echo "Generating TypeScript types from Rust structs..."

# Run only the export_bindings tests — these are auto-generated by ts-rs
# for every #[ts(export)] struct/enum. Much faster than running all tests.
cargo test -p claude-view-core export_bindings -- --nocapture 2>/dev/null || true
cargo test -p claude-view-server export_bindings -- --nocapture 2>/dev/null || true

echo ""
echo "=== Shared types (packages/shared/src/types/generated/) ==="
if ls packages/shared/src/types/generated/*.ts 1>/dev/null 2>&1; then
  ls packages/shared/src/types/generated/*.ts
else
  echo "(no shared .ts files generated)"
fi

echo ""
echo "=== Web types (apps/web/src/types/generated/) ==="
if ls apps/web/src/types/generated/*.ts 1>/dev/null 2>&1; then
  ls apps/web/src/types/generated/*.ts | wc -l | xargs -I{} echo "{} files"
else
  echo "(no web .ts files generated)"
fi
