//! Session retrieval and listing endpoints.

mod activity;
mod archive;
mod cost;
mod detail;
pub(crate) mod enrichment;
pub(crate) mod helpers;
mod list;
mod messages;
mod types;

// Test modules (split by concern to stay under 600 lines each)
#[cfg(test)]
mod tests_common;
#[cfg(test)]
mod tests_detail;
#[cfg(test)]
mod tests_hooks;
#[cfg(test)]
mod tests_list;
#[cfg(test)]
mod tests_messages;
#[cfg(test)]
mod tests_subagent;

// Re-export all public items so external code sees the same API as before.

// Types
pub use types::{
    ArchiveResponse, BulkArchiveRequest, BulkArchiveResponse, CommitWithTier, CostEstimate,
    DerivedMetrics, EstimateRequest, PaginatedBlocks, RichActivityParams, SessionActivityResponse,
    SessionDetail, SessionMessagesQuery, SessionsListQuery, SessionsListResponse,
    SparklineActivityParams,
};

// Helpers
pub(crate) use helpers::resolve_session_file_path;

// Handlers
pub use activity::{
    get_session_hook_events, list_branches, session_activity, session_activity_rich,
};
pub use archive::{
    archive_session_handler, bulk_archive_handler, bulk_unarchive_handler,
    unarchive_session_handler,
};
pub use cost::estimate_cost;
pub use detail::get_session_detail;
pub use list::list_sessions;
pub use messages::{
    get_session_messages_by_id, get_session_parsed, get_session_rich, get_subagent_messages,
};

// utoipa __path_* re-exports (generated by #[utoipa::path] in submodules)
#[allow(unused_imports)]
pub use activity::__path_get_session_hook_events;
#[allow(unused_imports)]
pub use activity::__path_list_branches;
#[allow(unused_imports)]
pub use activity::__path_session_activity;
#[allow(unused_imports)]
pub use activity::__path_session_activity_rich;
#[allow(unused_imports)]
pub use archive::__path_archive_session_handler;
#[allow(unused_imports)]
pub use archive::__path_bulk_archive_handler;
#[allow(unused_imports)]
pub use archive::__path_bulk_unarchive_handler;
#[allow(unused_imports)]
pub use archive::__path_unarchive_session_handler;
#[allow(unused_imports)]
pub use cost::__path_estimate_cost;
#[allow(unused_imports)]
pub use detail::__path_get_session_detail;
#[allow(unused_imports)]
pub use list::__path_list_sessions;
#[allow(unused_imports)]
pub use messages::__path_get_session_messages_by_id;
#[allow(unused_imports)]
pub use messages::__path_get_session_parsed;
#[allow(unused_imports)]
pub use messages::__path_get_session_rich;
#[allow(unused_imports)]
pub use messages::__path_get_subagent_messages;

// Router
use std::sync::Arc;

use axum::routing::{get, post};
use axum::Router;

use crate::state::AppState;

/// Create the sessions routes router.
pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route("/sessions", get(list_sessions))
        .route("/estimate", post(estimate_cost))
        .route("/sessions/activity", get(session_activity))
        .route("/sessions/activity/rich", get(session_activity_rich))
        .route("/sessions/archive", post(bulk_archive_handler))
        .route("/sessions/unarchive", post(bulk_unarchive_handler))
        .route("/sessions/{id}", get(get_session_detail))
        .route("/sessions/{id}/parsed", get(get_session_parsed))
        .route("/sessions/{id}/messages", get(get_session_messages_by_id))
        .route(
            "/sessions/{id}/subagents/{agent_id}/messages",
            get(get_subagent_messages),
        )
        .route("/sessions/{id}/rich", get(get_session_rich))
        .route("/sessions/{id}/hook-events", get(get_session_hook_events))
        .route("/sessions/{id}/archive", post(archive_session_handler))
        .route("/sessions/{id}/unarchive", post(unarchive_session_handler))
        .route("/branches", get(list_branches))
}
