use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "claude-view API",
        description = "Mission Control for Claude Code",
        version = env!("CARGO_PKG_VERSION"),
        license(name = "MIT"),
    ),
    paths(
        crate::routes::health::health_check,
        crate::routes::config::config,
        crate::routes::status::get_status,
        crate::routes::status::update_git_sync_interval,
        // Batch 1: Sessions
        crate::routes::sessions::list_sessions,
        crate::routes::sessions::get_session_detail,
        crate::routes::sessions::get_session_parsed,
        crate::routes::sessions::get_session_messages_by_id,
        crate::routes::sessions::get_session_rich,
        crate::routes::sessions::list_branches,
        crate::routes::sessions::session_activity,
        crate::routes::sessions::estimate_cost,
        crate::routes::sessions::archive_session_handler,
        crate::routes::sessions::unarchive_session_handler,
        crate::routes::sessions::bulk_archive_handler,
        crate::routes::sessions::bulk_unarchive_handler,
        crate::routes::sessions::get_session_hook_events,
        // Batch 1: Projects
        crate::routes::projects::list_projects,
        crate::routes::projects::list_project_sessions,
        crate::routes::projects::list_project_branches,
        // Batch 1: File History
        crate::routes::file_history::get_file_history,
        crate::routes::file_history::get_file_diff,
        // Batch 2: Live Monitoring
        crate::routes::live::live_stream,
        crate::routes::live::list_live_sessions,
        crate::routes::live::get_live_session,
        crate::routes::live::get_live_session_messages,
        crate::routes::live::get_session_statusline_debug,
        crate::routes::live::kill_session,
        crate::routes::live::bind_control,
        crate::routes::live::unbind_control,
        crate::routes::live::dismiss_session,
        crate::routes::live::dismiss_all_closed,
        crate::routes::live::get_live_summary,
        crate::routes::live::get_pricing,
        crate::routes::hooks::handle_hook,
        crate::routes::statusline::handle_statusline,
        crate::routes::monitor::monitor_stream,
        crate::routes::monitor::monitor_snapshot,
        // Batch 3: Analytics & Insights
        crate::routes::insights::get_insights,
        crate::routes::insights::get_categories,
        crate::routes::insights::get_insights_trends,
        crate::routes::insights::get_benchmarks,
        crate::routes::contributions::get_contributions,
        crate::routes::contributions::get_session_contribution,
        crate::routes::contributions::get_branch_sessions,
        crate::routes::stats::dashboard_stats,
        crate::routes::stats::storage_stats,
        crate::routes::stats::ai_generation_stats,
        crate::routes::trends::get_trends,
        crate::routes::score::get_fluency_score,
        crate::routes::invocables::list_invocables,
        crate::routes::invocables::stats_overview,
        crate::routes::invocables::stats_tokens,
        // Batch 4: Classify, Facets, Coaching, Search, Export, Turns, Plans, Models, Prompts
        crate::routes::classify::start_classification,
        crate::routes::classify::get_classification_status,
        crate::routes::classify::stream_classification,
        crate::routes::classify::cancel_classification,
        crate::routes::classify::classify_single_session,
        crate::routes::facets::facet_ingest_stream,
        crate::routes::facets::trigger_facet_ingest,
        crate::routes::facets::facet_stats,
        crate::routes::facets::facet_badges,
        crate::routes::facets::pattern_alert,
        crate::routes::coaching::list_rules,
        crate::routes::coaching::apply_rule,
        crate::routes::coaching::remove_rule,
        crate::routes::search::search_handler,
        crate::routes::export::export_sessions,
        crate::routes::turns::get_session_turns,
        crate::routes::plans::get_session_plans,
        crate::routes::models::list_models,
        crate::routes::prompts::list_prompts,
        crate::routes::prompts::get_prompt_stats,
        crate::routes::prompts::get_prompt_templates,
        // Batch 5: Reports, Share, OAuth, Pairing, Plugins, Workflows, IDE, Processes, Telemetry, Sync, System, Indexing, Jobs, Teams
        crate::routes::reports::list_reports,
        crate::routes::reports::get_preview,
        crate::routes::reports::get_report,
        crate::routes::reports::delete_report,
        crate::routes::reports::generate_report,
        crate::routes::share::create_share,
        crate::routes::share::revoke_share,
        crate::routes::share::list_shares,
        crate::routes::oauth::get_oauth_usage,
        crate::routes::oauth::post_oauth_usage_refresh,
        crate::routes::oauth::get_auth_identity,
        crate::routes::pairing::generate_qr,
        crate::routes::pairing::list_devices,
        crate::routes::pairing::unpair_device,
        crate::routes::plugins::list_plugins,
        crate::routes::plugins::list_marketplaces,
        crate::routes::plugin_ops::enqueue_op,
        crate::routes::plugin_ops::list_ops_handler,
        crate::routes::marketplace_refresh::refresh_all,
        crate::routes::marketplace_refresh::refresh_status,
        crate::routes::workflows::list_workflows,
        crate::routes::workflows::get_workflow,
        crate::routes::workflows::create_workflow,
        crate::routes::workflows::delete_workflow,
        crate::routes::workflows::chat_workflow,
        crate::routes::workflows::control_run,
        crate::routes::ide::get_detect,
        crate::routes::ide::post_open,
        crate::routes::processes::kill_process,
        crate::routes::processes::cleanup_processes,
        crate::routes::telemetry::set_consent,
        crate::routes::sync::trigger_git_sync,
        crate::routes::sync::git_sync_progress,
        crate::routes::sync::trigger_deep_index,
        crate::routes::indexing::indexing_status,
        crate::routes::indexing::indexing_progress,
        crate::routes::system::get_system_status,
        crate::routes::system::trigger_reindex,
        crate::routes::system::clear_cache,
        crate::routes::system::trigger_git_resync,
        crate::routes::system::reset_all,
        crate::routes::system::check_path,
        crate::routes::jobs::list_jobs,
        crate::routes::jobs::stream_jobs,
        crate::routes::teams::list_teams,
        crate::routes::teams::get_team,
        crate::routes::teams::get_team_inbox,
    ),
    components(schemas(
        crate::routes::health::HealthResponse,
        crate::routes::config::ConfigResponse,
        claude_view_core::telemetry_config::TelemetryStatus,
        claude_view_db::trends::IndexMetadata,
        crate::routes::status::UpdateGitSyncIntervalRequest,
        // Batch 1: Sessions schemas
        crate::routes::sessions::SessionsListResponse,
        crate::routes::sessions::SessionActivityResponse,
        crate::routes::sessions::SessionDetail,
        crate::routes::sessions::CommitWithTier,
        crate::routes::sessions::DerivedMetrics,
        crate::routes::sessions::EstimateRequest,
        crate::routes::sessions::CostEstimate,
        claude_view_core::SessionInfo,
        claude_view_core::ToolCounts,
        claude_view_core::task_files::TaskItem,
        // Batch 1: Projects schemas
        crate::routes::projects::BranchesResponse,
        claude_view_core::ProjectSummary,
        claude_view_core::SessionsPage,
        claude_view_db::BranchCount,
        // Batch 1: File History schemas
        claude_view_core::file_history::FileHistoryResponse,
        claude_view_core::file_history::FileChange,
        claude_view_core::file_history::FileVersion,
        claude_view_core::file_history::DiffStats,
        claude_view_core::file_history::DiffSummary,
        claude_view_core::file_history::FileDiffResponse,
        claude_view_core::file_history::DiffHunk,
        claude_view_core::file_history::DiffLine,
        claude_view_core::file_history::DiffLineKind,
        claude_view_db::ActivityPoint,
        // Batch 2: Live/Monitor schemas
        crate::routes::hooks::HookPayload,
        crate::routes::statusline::StatuslinePayload,
        crate::live::monitor::ResourceSnapshot,
        crate::live::monitor::SystemInfo,
        crate::live::monitor::ProcessGroup,
        crate::live::monitor::SessionResource,
        // Batch 3: Analytics & Insights schemas
        crate::routes::insights::CategoryBreakdown,
        crate::routes::insights::CategorySummary,
        crate::routes::insights::CategoryNode,
        crate::routes::insights::CategoriesResponse,
        crate::routes::insights::CategoriesMeta,
        crate::routes::insights::OverallAverages,
        crate::routes::insights::InsightsResponse,
        crate::routes::insights::InsightsOverview,
        crate::routes::insights::WorkBreakdown,
        crate::routes::insights::EfficiencyStats,
        crate::routes::insights::BestTimeStats,
        crate::routes::insights::PatternGroups,
        crate::routes::insights::ClassificationCoverage,
        crate::routes::insights::InsightsMeta,
        crate::routes::insights::InsightsTrendsMeta,
        crate::routes::insights::InsightsTrendsResponse,
        crate::routes::insights::BenchmarksResponseWithMeta,
        crate::routes::contributions::FluencyMetrics,
        crate::routes::contributions::OutputMetrics,
        crate::routes::contributions::EffectivenessMetrics,
        crate::routes::contributions::OverviewMetrics,
        crate::routes::contributions::EfficiencyMetrics,
        crate::routes::contributions::ContributionWarning,
        crate::routes::contributions::ContributionsResponse,
        crate::routes::contributions::SessionContributionResponse,
        crate::routes::contributions::BranchSessionsResponse,
        crate::routes::stats::CurrentPeriodMetrics,
        crate::routes::stats::ExtendedDashboardStats,
        crate::routes::stats::DashboardMeta,
        crate::routes::stats::DashboardRangesMeta,
        crate::routes::stats::DashboardTrends,
        crate::routes::stats::AIGenerationStatsResponse,
        crate::routes::stats::StorageStats,
        crate::routes::trends::WeekTrendsResponse,
        claude_view_db::InvocableWithCount,
        claude_view_db::StatsOverview,
        claude_view_db::TokenStats,
        // Batch 4: Classify, Facets, Coaching, Search, Export, Turns, Plans, Models, Prompts
        crate::routes::classify::ClassifyResponse,
        crate::routes::classify::CancelResponse,
        crate::routes::classify::ClassifyStatusResponse,
        crate::routes::classify::ClassifyProgressInfo,
        crate::routes::classify::ClassifyLastRun,
        crate::routes::classify::ClassifyErrorInfo,
        crate::routes::classify::ClassifySingleResponse,
        crate::routes::facets::FacetStatsResponse,
        crate::routes::facets::SessionBadge,
        crate::routes::facets::PatternAlertResponse,
        crate::routes::facets::TriggerResponse,
        crate::routes::coaching::CoachingRule,
        crate::routes::coaching::ListRulesResponse,
        crate::routes::coaching::RemoveRuleResponse,
        crate::routes::export::ExportedSession,
        crate::routes::export::ExportResponse,
        crate::routes::turns::TurnInfo,
        claude_view_core::plan_files::PlanDocument,
        claude_view_db::ModelWithStats,
        crate::routes::prompts::PromptInfo,
        crate::routes::prompts::PromptListResponse,
        crate::routes::prompts::PromptTemplateInfo,
        // Batch 5: Reports
        crate::routes::reports::GenerateRequest,
        claude_view_db::ReportRow,
        claude_view_db::ReportPreview,
        claude_view_db::ProjectPreview,
        // Batch 5: Share
        crate::routes::share::ShareResponse,
        // Batch 5: OAuth
        crate::routes::oauth::UsageTier,
        crate::routes::oauth::OAuthUsageResponse,
        crate::routes::oauth::AuthIdentityResponse,
        // Batch 5: Pairing
        crate::routes::pairing::QrPayload,
        crate::routes::pairing::PairedDeviceResponse,
        // Batch 5: Plugins
        crate::routes::plugins::PluginItem,
        crate::routes::plugins::PluginInfo,
        crate::routes::plugins::AvailablePlugin,
        crate::routes::plugins::UserItemInfo,
        crate::routes::plugins::PluginsResponse,
        crate::routes::plugins::MarketplaceInfo,
        crate::routes::plugins::PluginActionRequest,
        crate::routes::plugins::PluginActionResponse,
        // Batch 5: Plugin Ops
        crate::routes::plugin_ops::OpStatus,
        crate::routes::plugin_ops::PluginOp,
        // Batch 5: Marketplace Refresh
        crate::routes::marketplace_refresh::RefreshStatus,
        crate::routes::marketplace_refresh::RefreshOp,
        crate::routes::marketplace_refresh::RefreshAllRequest,
        crate::routes::marketplace_refresh::RefreshAllResponse,
        crate::routes::marketplace_refresh::RefreshStatusResponse,
        // Batch 5: Workflows
        crate::routes::workflows::WorkflowStageGate,
        crate::routes::workflows::WorkflowStage,
        crate::routes::workflows::WorkflowInput,
        crate::routes::workflows::WorkflowDefinition,
        crate::routes::workflows::WorkflowSummary,
        crate::routes::workflows::WorkflowDetail,
        crate::routes::workflows::CreateWorkflowRequest,
        // Batch 5: IDE
        crate::routes::ide::IdeInfo,
        crate::routes::ide::IdeDetectResponse,
        crate::routes::ide::OpenInIdeRequest,
        crate::routes::ide::OpenInIdeResponse,
        // Batch 5: Processes
        crate::routes::processes::KillProcessRequest,
        crate::routes::processes::KillProcessResponse,
        crate::routes::processes::KillTarget,
        crate::routes::processes::CleanupRequest,
        crate::routes::processes::CleanupResponse,
        crate::routes::processes::KillFailure,
        // Batch 5: Telemetry
        crate::routes::telemetry::ConsentRequest,
        crate::routes::telemetry::ConsentResponse,
        // Batch 5: Sync
        crate::routes::sync::SyncStatus,
        crate::routes::sync::SyncAcceptedResponse,
        // Batch 5: Indexing
        crate::routes::indexing::IndexingStatusResponse,
        // Batch 5: System
        crate::routes::system::SystemResponse,
        crate::routes::system::StorageInfo,
        crate::routes::system::PerformanceInfo,
        crate::routes::system::HealthInfo,
        crate::routes::system::IntegrityInfo,
        crate::routes::system::IntegrityCounterInfo,
        crate::routes::system::IndexRunInfo,
        crate::routes::system::ClassificationInfo,
        crate::routes::system::ActionResponse,
        crate::routes::system::ClearCacheResponse,
        crate::routes::system::CheckPathResponse,
        // Batch 5: Jobs
        crate::jobs::JobProgress,
        // Batch 5: Teams
        crate::teams::TeamSummary,
        crate::teams::TeamDetail,
        crate::teams::TeamMember,
        crate::teams::InboxMessage,
        crate::teams::InboxMessageType,
    )),
    tags(
        (name = "health", description = "Health checks and server status"),
        (name = "sessions", description = "Session CRUD, filtering, and export"),
        (name = "projects", description = "Project summaries and branches"),
        (name = "live", description = "Live session monitoring and control"),
        (name = "monitor", description = "System resource monitoring"),
        (name = "insights", description = "Behavioral insights and patterns"),
        (name = "contributions", description = "Contribution metrics"),
        (name = "stats", description = "Dashboard statistics and trends"),
        (name = "search", description = "Full-text search"),
        (name = "turns", description = "Per-turn session breakdown"),
        (name = "plans", description = "Session plans"),
        (name = "coaching", description = "Coaching rules management"),
        (name = "facets", description = "Session quality facets"),
        (name = "classify", description = "Session classification"),
        (name = "models", description = "Observed model usage"),
        (name = "export", description = "Data export (JSON/CSV)"),
        (name = "share", description = "Session sharing"),
        (name = "teams", description = "Team management"),
        (name = "plugins", description = "Plugin management"),
        (name = "oauth", description = "OAuth usage and identity"),
        (name = "settings", description = "App settings"),
        (name = "system", description = "System operations"),
        (name = "sync", description = "Git sync and indexing"),
        (name = "reports", description = "Generated reports"),
        (name = "prompts", description = "Prompt history and templates"),
        (name = "workflows", description = "Workflow management"),
        (name = "ide", description = "IDE integration"),
        (name = "pairing", description = "Device pairing"),
        (name = "jobs", description = "Background job tracking"),
        (name = "telemetry", description = "Telemetry consent"),
        (name = "processes", description = "Process management"),
    )
)]
pub struct ApiDoc;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn export_openapi_spec() {
        let spec = ApiDoc::openapi();
        let json = serde_json::to_string_pretty(&spec).unwrap();
        let out_path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../packages/plugin/scripts/openapi.json"
        );
        std::fs::write(out_path, json).unwrap();
        println!("OpenAPI spec written to {out_path}");
    }
}
