// crates/core/src/lib.rs
pub mod accumulator;
pub mod analytics_scope_contract;
pub mod block_accumulator;
pub mod block_types;
pub mod branch_filter;
pub mod category;
pub mod classification;
pub mod cli;
pub mod contribution;
pub mod credentials;
pub mod discovery;
pub mod error;
pub mod evidence_audit;
pub mod facets;
pub mod field_inventory;
pub mod file_history;
pub mod fluency_score;
pub mod insights;
pub mod invocation;
pub mod live_parser;
pub mod llm;
pub mod metrics;
pub mod parser;
pub mod paths;
pub mod patterns;
pub mod phase;
pub mod pipeline_checks;
pub mod plan_files;
pub mod pricing;
pub mod progress;
pub mod prompt_history;
pub mod prompt_templates;
pub mod registry;
pub mod report;
pub mod session_index;
pub mod subagent;
pub mod tail;
pub mod task_files;
pub mod telemetry_config;
pub mod time_range_contract;
pub mod types;
pub mod work_type;

pub use analytics_scope_contract::*;
pub use block_types::*;
pub use branch_filter::*;
pub use category::*;
pub use cli::{resolved_cli_path, ClaudeCliStatus};
pub use contribution::*;
pub use discovery::*;
pub use error::*;
pub use invocation::*;
pub use metrics::*;
pub use parser::*;
pub use phase::{
    classify_window, dominant_phase, PhaseClassifier, PhaseHistory, PhaseLabel, SessionPhase,
    StepSignals,
};
pub use registry::*;
pub use session_index::*;
pub use time_range_contract::*;
pub use types::*;
pub use work_type::*;
