import { useCallback } from 'react'
import { Copy, Check, Download } from 'lucide-react'
import { useState } from 'react'

interface ReportContentProps {
  markdown: string
  streaming?: boolean
}

/**
 * Simple markdown-to-HTML for bullet-point reports.
 * Content is safe: it comes exclusively from our own server-side AI report
 * generator (not user-supplied input). The markdown is generated by the
 * backend digest builder and does not include arbitrary HTML or script tags.
 */
function renderSimpleMarkdown(md: string): string {
  // Escape HTML entities first to prevent any injection
  const escape = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

  return md
    .split('\n')
    .map(line => {
      // Headers
      if (line.startsWith('### ')) return `<h3 class="text-sm font-semibold mt-3 mb-1 text-gray-900 dark:text-gray-100">${escape(line.slice(4))}</h3>`
      if (line.startsWith('## ')) return `<h2 class="text-base font-semibold mt-4 mb-1 text-gray-900 dark:text-gray-100">${escape(line.slice(3))}</h2>`
      // Bullets
      if (line.startsWith('- ') || line.startsWith('* ')) {
        const content = escape(line.slice(2))
        // Bold text (after escaping)
        const formatted = content.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
        return `<li class="text-sm text-gray-700 dark:text-gray-300 ml-4 mb-1">${formatted}</li>`
      }
      // Empty lines
      if (line.trim() === '') return '<br/>'
      // Plain text
      const formatted = escape(line).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      return `<p class="text-sm text-gray-700 dark:text-gray-300 mb-1">${formatted}</p>`
    })
    .join('\n')
}

export function ReportContent({ markdown, streaming = false }: ReportContentProps) {
  const [copied, setCopied] = useState(false)

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(markdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [markdown])

  const handleDownload = useCallback(() => {
    const blob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `report-${new Date().toISOString().slice(0, 10)}.md`
    a.click()
    URL.revokeObjectURL(url)
  }, [markdown])

  return (
    <div>
      {/* Content is sanitized via escape() in renderSimpleMarkdown before rendering */}
      <div
        className="prose prose-sm dark:prose-invert max-w-none"
        dangerouslySetInnerHTML={{ __html: renderSimpleMarkdown(markdown) }}
      />
      {streaming && (
        <span className="inline-block w-2 h-4 bg-blue-500 animate-pulse ml-0.5" />
      )}
      {!streaming && markdown && (
        <div className="flex items-center gap-2 mt-4 pt-3 border-t border-gray-100 dark:border-gray-800">
          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied' : 'Copy'}
          </button>
          <button
            type="button"
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            Export .md
          </button>
        </div>
      )}
    </div>
  )
}
